        .label = "block <user|ip|list|confirm>",
            "Hide messages from a user or IP locally (%sblock list to review; use %sblock confirm <user> <only|ip> when prompted).",
            "사용자 또는 IP의 메시지를 차단합니다 (%sblock list로 확인, 제공자 안내 시 %sblock confirm <user> <only|ip>으로 확정).",
            "ユーザーやIPのメッセージをローカルで非表示にします（確認は %sblock list、プロバイダー警告時は %sblock confirm <user> <only|ip>）。",
            "本地屏蔽某用户或 IP 的消息（用 %sblock list 查看，出现提供商提示时用 %sblock confirm <user> <only|ip> 确认）。",
            "Скрыть сообщения пользователя или IP локально (просмотр через %sblock list, подтверждение подсказки провайдера — %sblock confirm <user> <only|ip>).",
        .label = "unblock <user|ip|all>",
